// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWWlDm9I5dUc8vF9UgvnBSdjKLZ7omS70',
    appId: '1:41263393040:web:c6f47099b7eb9b6926dd95',
    messagingSenderId: '41263393040',
    projectId: 'attea-88b9a',
    authDomain: 'attea-88b9a.firebaseapp.com',
    storageBucket: 'attea-88b9a.firebasestorage.app',
    measurementId: 'G-DLRGY76748',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDM8fwLznPHey4bqNid8OSPzSJppxYlXas',
    appId: '1:41263393040:android:cbcef749f7b820a926dd95',
    messagingSenderId: '41263393040',
    projectId: 'attea-88b9a',
    storageBucket: 'attea-88b9a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNiSU9k7U38OShFBL1prU4hnWu3DvUNik',
    appId: '1:41263393040:ios:d1af0eb772d771ba26dd95',
    messagingSenderId: '41263393040',
    projectId: 'attea-88b9a',
    storageBucket: 'attea-88b9a.firebasestorage.app',
    iosBundleId: 'com.example.bakingClubApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDNiSU9k7U38OShFBL1prU4hnWu3DvUNik',
    appId: '1:41263393040:ios:d1af0eb772d771ba26dd95',
    messagingSenderId: '41263393040',
    projectId: 'attea-88b9a',
    storageBucket: 'attea-88b9a.firebasestorage.app',
    iosBundleId: 'com.example.bakingClubApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCWWlDm9I5dUc8vF9UgvnBSdjKLZ7omS70',
    appId: '1:41263393040:web:86a834090323ebf126dd95',
    messagingSenderId: '41263393040',
    projectId: 'attea-88b9a',
    authDomain: 'attea-88b9a.firebaseapp.com',
    storageBucket: 'attea-88b9a.firebasestorage.app',
    measurementId: 'G-DGVGV785EC',
  );
}